package consterrors

import "errors"

var ErrEmptyPassword error = errors.New("empty password")
var ErrPasswordToShort error = errors.New("password shorter than 10 characters")
var ErrPasswordMissingElements error = errors.New("password must containt lower case, upper case, digit and at least a symbol")
var ErrEmptyEmail error = errors.New("no email supplied")
var ErrEmptyToken error = errors.New("no token supplied")
var ErrInvalidCredentials error = errors.New("invalid credentials")
var ErrAlreadyConfirmed error = errors.New("already confirmed this request")
var ErrInvalidToken error = errors.New("invalid token")
var ErrNoToken error = errors.New("no token")
var ErrNoGitToken error = errors.New("no git token")
var ErrNotLoggedIn error = errors.New("not logged in")
var ErrEmptyOfferName error = errors.New("offer name cannot be empty")
var ErrNegativeMaxRunners error = errors.New("negative max runners")
var ErrNegativeBasePrice error = errors.New("negative base price")
var ErrEmptyCurrency = errors.New("empty currency")
var ErrZerodMaxSyncRate = errors.New("zero max sync rate")
var ErrNoGitClient = errors.New("no git client")
var ErrNoUserId = errors.New("no user id")
var ErrRecordNotFound = errors.New("record not found")
var ErrInvalidNumJobs = errors.New("invalid num jobs")
var ErrNoID = errors.New("no id")
var ErrNoStartOrEndDate = errors.New("no start or end date")
var ErrInvalidGitlabJob = errors.New("invalid gitlab job")
var ErrInvalidID = errors.New("invalid id")
